package claudesdk

// Environment variable constants used by the Claude Code Agent SDK.
// These can be set in the environment or via ClaudeAgentOptions.Env.
//
// SDK-specific variables (used internally by the SDK/CLI handshake):

const (
	// CLAUDE_CODE_CONFIG_DIR overrides the default Claude config directory (~/.claude).
	CLAUDE_CODE_CONFIG_DIR = "CLAUDE_CONFIG_DIR"

	// CLAUDE_CODE_STREAM_CLOSE_TIMEOUT sets the initialize handshake timeout in milliseconds.
	// Default: "60000" (60 seconds).
	CLAUDE_CODE_STREAM_CLOSE_TIMEOUT = "CLAUDE_CODE_STREAM_CLOSE_TIMEOUT"

	// CLAUDE_CODE_SKIP_VERSION_CHECK skips the CLI version validation when set.
	CLAUDE_CODE_SKIP_VERSION_CHECK = "CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK"

	// CLAUDE_CODE_ENABLE_FILE_CHECKPOINTING enables file state checkpointing when set to "true".
	CLAUDE_CODE_ENABLE_FILE_CHECKPOINTING = "CLAUDE_CODE_ENABLE_SDK_FILE_CHECKPOINTING"

	// CLAUDE_CODE_ENTRYPOINT identifies the SDK entry point. The Go SDK sets this to "sdk-go".
	CLAUDE_CODE_ENTRYPOINT = "CLAUDE_CODE_ENTRYPOINT"

	// CLAUDE_CODE_SDK_VERSION is set by the SDK to its version string.
	CLAUDE_CODE_SDK_VERSION = "CLAUDE_AGENT_SDK_VERSION"

	// CLAUDE_CODE_NESTING_FILTER is filtered out to prevent recursive CLI nesting.
	CLAUDE_CODE_NESTING_FILTER = "CLAUDECODE"

	// CLAUDE_CODE_SDK_CLIENT_APP identifies the client application using the SDK.
	CLAUDE_CODE_SDK_CLIENT_APP = "CLAUDE_AGENT_SDK_CLIENT_APP"

	// CLAUDE_CODE_SDK_DISABLE_BUILTIN_AGENTS disables built-in agents when set.
	CLAUDE_CODE_SDK_DISABLE_BUILTIN_AGENTS = "CLAUDE_AGENT_SDK_DISABLE_BUILTIN_AGENTS"

	// CLAUDE_CODE_SDK_MCP_NO_PREFIX skips MCP tool name prefixing.
	CLAUDE_CODE_SDK_MCP_NO_PREFIX = "CLAUDE_AGENT_SDK_MCP_NO_PREFIX"
)

// Claude Code CLI environment variables.
// These configure the Claude Code CLI process behavior when set in the environment
// or passed via ClaudeAgentOptions.Env.

const (
	// --- API & Authentication ---

	// CLAUDE_CODE_API_KEY is the Anthropic API key.
	CLAUDE_CODE_API_KEY = "CLAUDE_API_KEY"

	// CLAUDE_CODE_API_BASE_URL overrides the Anthropic API base URL.
	CLAUDE_CODE_API_BASE_URL = "CLAUDE_CODE_API_BASE_URL"

	// CLAUDE_CODE_OAUTH_TOKEN provides an OAuth token for authentication.
	CLAUDE_CODE_OAUTH_TOKEN = "CLAUDE_CODE_OAUTH_TOKEN"

	// CLAUDE_CODE_OAUTH_REFRESH_TOKEN provides an OAuth refresh token.
	CLAUDE_CODE_OAUTH_REFRESH_TOKEN = "CLAUDE_CODE_OAUTH_REFRESH_TOKEN"

	// CLAUDE_CODE_MODEL overrides the default model.
	CLAUDE_CODE_MODEL = "ANTHROPIC_MODEL"

	// CLAUDE_CODE_SMALL_FAST_MODEL overrides the small/fast model.
	CLAUDE_CODE_SMALL_FAST_MODEL = "ANTHROPIC_SMALL_FAST_MODEL"

	// --- Cloud Provider ---

	// CLAUDE_CODE_USE_BEDROCK enables AWS Bedrock as the provider.
	CLAUDE_CODE_USE_BEDROCK = "CLAUDE_CODE_USE_BEDROCK"

	// CLAUDE_CODE_USE_VERTEX enables Google Vertex AI as the provider.
	CLAUDE_CODE_USE_VERTEX = "CLAUDE_CODE_USE_VERTEX"

	// CLAUDE_CODE_USE_FOUNDRY enables Anthropic Foundry as the provider.
	CLAUDE_CODE_USE_FOUNDRY = "CLAUDE_CODE_USE_FOUNDRY"

	// CLAUDE_CODE_SKIP_BEDROCK_AUTH skips Bedrock authentication.
	CLAUDE_CODE_SKIP_BEDROCK_AUTH = "CLAUDE_CODE_SKIP_BEDROCK_AUTH"

	// CLAUDE_CODE_SKIP_VERTEX_AUTH skips Vertex authentication.
	CLAUDE_CODE_SKIP_VERTEX_AUTH = "CLAUDE_CODE_SKIP_VERTEX_AUTH"

	// CLAUDE_CODE_SKIP_FOUNDRY_AUTH skips Foundry authentication.
	CLAUDE_CODE_SKIP_FOUNDRY_AUTH = "CLAUDE_CODE_SKIP_FOUNDRY_AUTH"

	// --- Session & Debugging ---

	// CLAUDE_CODE_DEBUG enables debug mode.
	CLAUDE_CODE_DEBUG = "CLAUDE_DEBUG"

	// CLAUDE_CODE_DEBUG_LOGS_DIR sets the debug log directory.
	CLAUDE_CODE_DEBUG_LOGS_DIR = "CLAUDE_CODE_DEBUG_LOGS_DIR"

	// CLAUDE_CODE_DEBUG_LOG_LEVEL sets the debug log level.
	CLAUDE_CODE_DEBUG_LOG_LEVEL = "CLAUDE_CODE_DEBUG_LOG_LEVEL"

	// CLAUDE_CODE_SESSION_ID sets the session ID.
	CLAUDE_CODE_SESSION_ID = "CLAUDE_CODE_SESSION_ID"

	// CLAUDE_CODE_SESSION_NAME sets the session name.
	CLAUDE_CODE_SESSION_NAME = "CLAUDE_CODE_SESSION_NAME"

	// CLAUDE_CODE_PARENT_SESSION_ID sets the parent session for sub-agents.
	CLAUDE_CODE_PARENT_SESSION_ID = "CLAUDE_CODE_PARENT_SESSION_ID"

	// CLAUDE_CODE_JSONL_TRANSCRIPT enables JSONL transcript output.
	CLAUDE_CODE_JSONL_TRANSCRIPT = "CLAUDE_CODE_JSONL_TRANSCRIPT"

	// CLAUDE_CODE_SESSION_LOG enables session logging.
	CLAUDE_CODE_SESSION_LOG = "CLAUDE_CODE_SESSION_LOG"

	// --- Feature Flags ---

	// CLAUDE_CODE_DISABLE_AUTO_MEMORY disables auto memory.
	CLAUDE_CODE_DISABLE_AUTO_MEMORY = "CLAUDE_CODE_DISABLE_AUTO_MEMORY"

	// CLAUDE_CODE_DISABLE_BACKGROUND_TASKS disables background tasks.
	CLAUDE_CODE_DISABLE_BACKGROUND_TASKS = "CLAUDE_CODE_DISABLE_BACKGROUND_TASKS"

	// CLAUDE_CODE_DISABLE_CRON disables cron jobs.
	CLAUDE_CODE_DISABLE_CRON = "CLAUDE_CODE_DISABLE_CRON"

	// CLAUDE_CODE_DISABLE_FAST_MODE disables fast mode.
	CLAUDE_CODE_DISABLE_FAST_MODE = "CLAUDE_CODE_DISABLE_FAST_MODE"

	// CLAUDE_CODE_DISABLE_THINKING disables thinking/reasoning.
	CLAUDE_CODE_DISABLE_THINKING = "CLAUDE_CODE_DISABLE_THINKING"

	// CLAUDE_CODE_DISABLE_CLAUDE_MDS disables reading CLAUDE.md files.
	CLAUDE_CODE_DISABLE_CLAUDE_MDS = "CLAUDE_CODE_DISABLE_CLAUDE_MDS"

	// CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS disables git-based instructions.
	CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS = "CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS"

	// CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC disables non-essential network traffic.
	CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC"

	// CLAUDE_CODE_ENABLE_TASKS enables task tracking.
	CLAUDE_CODE_ENABLE_TASKS = "CLAUDE_CODE_ENABLE_TASKS"

	// CLAUDE_CODE_ENABLE_TELEMETRY enables telemetry collection.
	CLAUDE_CODE_ENABLE_TELEMETRY = "CLAUDE_CODE_ENABLE_TELEMETRY"

	// CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES enables partial message streaming.
	CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES = "CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES"

	// --- Model & Thinking ---

	// CLAUDE_CODE_EFFORT_LEVEL sets the effort level (low, medium, high, max).
	CLAUDE_CODE_EFFORT_LEVEL = "CLAUDE_CODE_EFFORT_LEVEL"

	// CLAUDE_CODE_MAX_CONTEXT_TOKENS sets the max context window tokens.
	CLAUDE_CODE_MAX_CONTEXT_TOKENS = "CLAUDE_CODE_MAX_CONTEXT_TOKENS"

	// CLAUDE_CODE_MAX_OUTPUT_TOKENS sets the max output tokens.
	CLAUDE_CODE_MAX_OUTPUT_TOKENS = "CLAUDE_CODE_MAX_OUTPUT_TOKENS"

	// CLAUDE_CODE_SUBAGENT_MODEL overrides the model for sub-agents.
	CLAUDE_CODE_SUBAGENT_MODEL = "CLAUDE_CODE_SUBAGENT_MODEL"

	// CLAUDE_CODE_AUTO_MODE_MODEL overrides the model for auto mode.
	CLAUDE_CODE_AUTO_MODE_MODEL = "CLAUDE_CODE_AUTO_MODE_MODEL"

	// --- Sandbox & Environment ---

	// CLAUDE_CODE_FORCE_SANDBOX forces sandbox mode.
	CLAUDE_CODE_FORCE_SANDBOX = "CLAUDE_CODE_FORCE_SANDBOX"

	// CLAUDE_CODE_BUBBLEWRAP enables bubblewrap sandbox on Linux.
	CLAUDE_CODE_BUBBLEWRAP = "CLAUDE_CODE_BUBBLEWRAP"

	// CLAUDE_CODE_SHELL overrides the shell used for bash commands.
	CLAUDE_CODE_SHELL = "CLAUDE_CODE_SHELL"

	// CLAUDE_CODE_TMPDIR overrides the temporary directory.
	CLAUDE_CODE_TMPDIR = "CLAUDE_CODE_TMPDIR"

	// CLAUDE_CODE_ENVIRONMENT_KIND describes the environment (e.g., "docker", "ssh").
	CLAUDE_CODE_ENVIRONMENT_KIND = "CLAUDE_CODE_ENVIRONMENT_KIND"

	// CLAUDE_CODE_REMOTE enables remote mode.
	CLAUDE_CODE_REMOTE = "CLAUDE_CODE_REMOTE"

	// --- MCP ---

	// CLAUDE_CODE_MCP_TIMEOUT sets the MCP server connection timeout.
	CLAUDE_CODE_MCP_TIMEOUT = "MCP_TIMEOUT"

	// CLAUDE_CODE_MCP_TOOL_TIMEOUT sets the MCP tool execution timeout.
	CLAUDE_CODE_MCP_TOOL_TIMEOUT = "MCP_TOOL_TIMEOUT"

	// CLAUDE_CODE_MAX_MCP_OUTPUT_TOKENS limits MCP output tokens.
	CLAUDE_CODE_MAX_MCP_OUTPUT_TOKENS = "MAX_MCP_OUTPUT_TOKENS"

	// --- Bash Tool ---

	// CLAUDE_CODE_BASH_DEFAULT_TIMEOUT_MS sets the default bash command timeout.
	CLAUDE_CODE_BASH_DEFAULT_TIMEOUT_MS = "BASH_DEFAULT_TIMEOUT_MS"

	// CLAUDE_CODE_BASH_MAX_TIMEOUT_MS sets the max bash command timeout.
	CLAUDE_CODE_BASH_MAX_TIMEOUT_MS = "BASH_MAX_TIMEOUT_MS"

	// CLAUDE_CODE_BASH_MAX_OUTPUT_LENGTH limits bash command output length.
	CLAUDE_CODE_BASH_MAX_OUTPUT_LENGTH = "BASH_MAX_OUTPUT_LENGTH"

	// --- Proxy & TLS ---

	// CLAUDE_CODE_HTTP_PROXY sets the HTTP proxy.
	CLAUDE_CODE_HTTP_PROXY = "HTTP_PROXY"

	// CLAUDE_CODE_HTTPS_PROXY sets the HTTPS proxy.
	CLAUDE_CODE_HTTPS_PROXY = "HTTPS_PROXY"

	// CLAUDE_CODE_NO_PROXY sets the no-proxy list.
	CLAUDE_CODE_NO_PROXY = "NO_PROXY"

	// CLAUDE_CODE_CLIENT_CERT sets the client certificate path for mTLS.
	CLAUDE_CODE_CLIENT_CERT = "CLAUDE_CODE_CLIENT_CERT"

	// CLAUDE_CODE_CLIENT_KEY sets the client key path for mTLS.
	CLAUDE_CODE_CLIENT_KEY = "CLAUDE_CODE_CLIENT_KEY"

	// --- Telemetry (OpenTelemetry) ---

	// CLAUDE_CODE_OTEL_ENDPOINT sets the OTLP exporter endpoint.
	CLAUDE_CODE_OTEL_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"

	// CLAUDE_CODE_OTEL_HEADERS sets the OTLP exporter headers.
	CLAUDE_CODE_OTEL_HEADERS = "OTEL_EXPORTER_OTLP_HEADERS"

	// --- Anthropic API ---

	// CLAUDE_CODE_ANTHROPIC_API_KEY is the Anthropic API key (alternative).
	CLAUDE_CODE_ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"

	// CLAUDE_CODE_ANTHROPIC_BASE_URL overrides the Anthropic API base URL.
	CLAUDE_CODE_ANTHROPIC_BASE_URL = "ANTHROPIC_BASE_URL"

	// CLAUDE_CODE_ANTHROPIC_BETAS sets API beta flags.
	CLAUDE_CODE_ANTHROPIC_BETAS = "ANTHROPIC_BETAS"

	// CLAUDE_CODE_ANTHROPIC_CUSTOM_HEADERS sets custom API headers.
	CLAUDE_CODE_ANTHROPIC_CUSTOM_HEADERS = "ANTHROPIC_CUSTOM_HEADERS"

	// --- Prompt Caching ---

	// CLAUDE_CODE_DISABLE_PROMPT_CACHING disables prompt caching.
	CLAUDE_CODE_DISABLE_PROMPT_CACHING = "DISABLE_PROMPT_CACHING"

	// CLAUDE_CODE_DISABLE_TELEMETRY disables telemetry.
	CLAUDE_CODE_DISABLE_TELEMETRY = "DISABLE_TELEMETRY"

	// CLAUDE_CODE_DISABLE_ERROR_REPORTING disables error reporting.
	CLAUDE_CODE_DISABLE_ERROR_REPORTING = "DISABLE_ERROR_REPORTING"

	// --- Misc ---

	// CLAUDE_CODE_MAX_RETRIES sets the max API retry count.
	CLAUDE_CODE_MAX_RETRIES = "CLAUDE_CODE_MAX_RETRIES"

	// CLAUDE_CODE_IDLE_THRESHOLD_MINUTES sets the idle timeout threshold.
	CLAUDE_CODE_IDLE_THRESHOLD_MINUTES = "CLAUDE_CODE_IDLE_THRESHOLD_MINUTES"

	// CLAUDE_CODE_BRIEF enables brief output mode.
	CLAUDE_CODE_BRIEF = "CLAUDE_CODE_BRIEF"

	// CLAUDE_CODE_TAGS sets session tags.
	CLAUDE_CODE_TAGS = "CLAUDE_CODE_TAGS"

	// CLAUDE_CODE_EXTRA_BODY sets extra body fields for API requests.
	CLAUDE_CODE_EXTRA_BODY = "CLAUDE_CODE_EXTRA_BODY"

	// CLAUDE_CODE_EXTRA_METADATA sets extra metadata for API requests.
	CLAUDE_CODE_EXTRA_METADATA = "CLAUDE_CODE_EXTRA_METADATA"
)

// SDKVersion is the current version of the Go Agent SDK.
const SDKVersion = "0.1.0"

// MinimumClaudeCodeVersion is the minimum required Claude Code CLI version.
const MinimumClaudeCodeVersion = "2.0.0"

// SDKEntrypoint identifies this SDK in the CLAUDE_CODE_ENTRYPOINT variable.
const SDKEntrypoint = "sdk-go"
