package claudesdk

// Environment variable constants used by the Claude Code Agent SDK.
// These can be set in the environment or via ClaudeAgentOptions.Env.
//
// Naming convention: Go constant name = CLAUDE_CODE_<CATEGORY>_<NAME>
// The string value is the actual environment variable name read by the CLI.

// ═══════════════════════════════════════════════════
//   SDK-specific variables (SDK/CLI handshake)
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_CONFIG_DIR overrides the default Claude config directory (~/.claude).
	CLAUDE_CODE_CONFIG_DIR = "CLAUDE_CONFIG_DIR"

	// CLAUDE_CODE_STREAM_CLOSE_TIMEOUT sets the initialize handshake timeout in milliseconds.
	CLAUDE_CODE_STREAM_CLOSE_TIMEOUT = "CLAUDE_CODE_STREAM_CLOSE_TIMEOUT"

	// CLAUDE_CODE_SKIP_VERSION_CHECK skips the CLI version validation when set.
	CLAUDE_CODE_SKIP_VERSION_CHECK = "CLAUDE_AGENT_SDK_SKIP_VERSION_CHECK"

	// CLAUDE_CODE_ENABLE_FILE_CHECKPOINTING enables file state checkpointing when set to "true".
	CLAUDE_CODE_ENABLE_FILE_CHECKPOINTING = "CLAUDE_CODE_ENABLE_SDK_FILE_CHECKPOINTING"

	// CLAUDE_CODE_ENTRYPOINT identifies the SDK entry point. The Go SDK sets this to "sdk-go".
	CLAUDE_CODE_ENTRYPOINT = "CLAUDE_CODE_ENTRYPOINT"

	// CLAUDE_CODE_SDK_VERSION is set by the SDK to its version string.
	CLAUDE_CODE_SDK_VERSION = "CLAUDE_AGENT_SDK_VERSION"

	// CLAUDE_CODE_NESTING_FILTER is filtered out to prevent recursive CLI nesting.
	CLAUDE_CODE_NESTING_FILTER = "CLAUDECODE"

	// CLAUDE_CODE_SDK_CLIENT_APP identifies the client application using the SDK.
	CLAUDE_CODE_SDK_CLIENT_APP = "CLAUDE_AGENT_SDK_CLIENT_APP"

	// CLAUDE_CODE_SDK_DISABLE_BUILTIN_AGENTS disables built-in agents when set.
	CLAUDE_CODE_SDK_DISABLE_BUILTIN_AGENTS = "CLAUDE_AGENT_SDK_DISABLE_BUILTIN_AGENTS"

	// CLAUDE_CODE_SDK_MCP_NO_PREFIX skips MCP tool name prefixing.
	CLAUDE_CODE_SDK_MCP_NO_PREFIX = "CLAUDE_AGENT_SDK_MCP_NO_PREFIX"
)

// ═══════════════════════════════════════════════════
//   API & Authentication
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_API_KEY is the Claude API key.
	CLAUDE_CODE_API_KEY = "CLAUDE_API_KEY"

	// CLAUDE_CODE_API_BASE_URL overrides the Claude Code API base URL.
	CLAUDE_CODE_API_BASE_URL = "CLAUDE_CODE_API_BASE_URL"

	// CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR provides the API key via a file descriptor.
	CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR = "CLAUDE_CODE_API_KEY_FILE_DESCRIPTOR"

	// CLAUDE_CODE_API_KEY_HELPER_TTL_MS sets the TTL for API key helper caching in ms.
	CLAUDE_CODE_API_KEY_HELPER_TTL_MS = "CLAUDE_CODE_API_KEY_HELPER_TTL_MS"

	// CLAUDE_CODE_OAUTH_TOKEN provides an OAuth token for authentication.
	CLAUDE_CODE_OAUTH_TOKEN = "CLAUDE_CODE_OAUTH_TOKEN"

	// CLAUDE_CODE_OAUTH_REFRESH_TOKEN provides an OAuth refresh token.
	CLAUDE_CODE_OAUTH_REFRESH_TOKEN = "CLAUDE_CODE_OAUTH_REFRESH_TOKEN"

	// CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR provides the OAuth token via a file descriptor.
	CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR = "CLAUDE_CODE_OAUTH_TOKEN_FILE_DESCRIPTOR"

	// CLAUDE_CODE_OAUTH_CLIENT_ID overrides the OAuth client ID.
	CLAUDE_CODE_OAUTH_CLIENT_ID = "CLAUDE_CODE_OAUTH_CLIENT_ID"

	// CLAUDE_CODE_OAUTH_SCOPES sets OAuth scopes.
	CLAUDE_CODE_OAUTH_SCOPES = "CLAUDE_CODE_OAUTH_SCOPES"

	// CLAUDE_CODE_CUSTOM_OAUTH_URL sets a custom OAuth URL.
	CLAUDE_CODE_CUSTOM_OAUTH_URL = "CLAUDE_CODE_CUSTOM_OAUTH_URL"

	// CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR provides websocket auth via file descriptor.
	CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR = "CLAUDE_CODE_WEBSOCKET_AUTH_FILE_DESCRIPTOR"

	// CLAUDE_CODE_SESSION_ACCESS_TOKEN provides a session access token.
	CLAUDE_CODE_SESSION_ACCESS_TOKEN = "CLAUDE_CODE_SESSION_ACCESS_TOKEN"

	// CLAUDE_CODE_ATTRIBUTION_HEADER sets the attribution header for API requests.
	CLAUDE_CODE_ATTRIBUTION_HEADER = "CLAUDE_CODE_ATTRIBUTION_HEADER"

	// CLAUDE_CODE_ACCOUNT_UUID sets the account UUID.
	CLAUDE_CODE_ACCOUNT_UUID = "CLAUDE_CODE_ACCOUNT_UUID"

	// CLAUDE_CODE_ACCOUNT_TAGGED_ID sets the account tagged ID.
	CLAUDE_CODE_ACCOUNT_TAGGED_ID = "CLAUDE_CODE_ACCOUNT_TAGGED_ID"

	// CLAUDE_CODE_ORGANIZATION_UUID sets the organization UUID.
	CLAUDE_CODE_ORGANIZATION_UUID = "CLAUDE_CODE_ORGANIZATION_UUID"

	// CLAUDE_CODE_USER_EMAIL sets the user email.
	CLAUDE_CODE_USER_EMAIL = "CLAUDE_CODE_USER_EMAIL"

	// CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST indicates provider is managed by host.
	CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST = "CLAUDE_CODE_PROVIDER_MANAGED_BY_HOST"
)

// ═══════════════════════════════════════════════════
//   Anthropic API
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_ANTHROPIC_API_KEY is the Anthropic API key (alternative).
	CLAUDE_CODE_ANTHROPIC_API_KEY = "ANTHROPIC_API_KEY"

	// CLAUDE_CODE_ANTHROPIC_AUTH_TOKEN is the Anthropic auth token.
	CLAUDE_CODE_ANTHROPIC_AUTH_TOKEN = "ANTHROPIC_AUTH_TOKEN"

	// CLAUDE_CODE_ANTHROPIC_BASE_URL overrides the Anthropic API base URL.
	CLAUDE_CODE_ANTHROPIC_BASE_URL = "ANTHROPIC_BASE_URL"

	// CLAUDE_CODE_ANTHROPIC_BETAS sets API beta flags.
	CLAUDE_CODE_ANTHROPIC_BETAS = "ANTHROPIC_BETAS"

	// CLAUDE_CODE_ANTHROPIC_CUSTOM_HEADERS sets custom API headers.
	CLAUDE_CODE_ANTHROPIC_CUSTOM_HEADERS = "ANTHROPIC_CUSTOM_HEADERS"

	// CLAUDE_CODE_ANTHROPIC_UNIX_SOCKET sets the Unix socket path for Anthropic API.
	CLAUDE_CODE_ANTHROPIC_UNIX_SOCKET = "ANTHROPIC_UNIX_SOCKET"

	// CLAUDE_CODE_ANTHROPIC_CUSTOM_MODEL_OPTION sets a custom model option.
	CLAUDE_CODE_ANTHROPIC_CUSTOM_MODEL_OPTION = "ANTHROPIC_CUSTOM_MODEL_OPTION"

	// CLAUDE_CODE_ANTHROPIC_CUSTOM_MODEL_OPTION_NAME sets the custom model option name.
	CLAUDE_CODE_ANTHROPIC_CUSTOM_MODEL_OPTION_NAME = "ANTHROPIC_CUSTOM_MODEL_OPTION_NAME"

	// CLAUDE_CODE_ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION sets the custom model option description.
	CLAUDE_CODE_ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION = "ANTHROPIC_CUSTOM_MODEL_OPTION_DESCRIPTION"
)

// ═══════════════════════════════════════════════════
//   Model & Thinking
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_MODEL overrides the default model.
	CLAUDE_CODE_MODEL = "ANTHROPIC_MODEL"

	// CLAUDE_CODE_SMALL_FAST_MODEL overrides the small/fast model.
	CLAUDE_CODE_SMALL_FAST_MODEL = "ANTHROPIC_SMALL_FAST_MODEL"

	// CLAUDE_CODE_SMALL_FAST_MODEL_AWS_REGION overrides the AWS region for the small/fast model.
	CLAUDE_CODE_SMALL_FAST_MODEL_AWS_REGION = "ANTHROPIC_SMALL_FAST_MODEL_AWS_REGION"

	// CLAUDE_CODE_DEFAULT_HAIKU_MODEL overrides the default Haiku model.
	CLAUDE_CODE_DEFAULT_HAIKU_MODEL = "ANTHROPIC_DEFAULT_HAIKU_MODEL"

	// CLAUDE_CODE_DEFAULT_HAIKU_MODEL_NAME sets the display name for the default Haiku model.
	CLAUDE_CODE_DEFAULT_HAIKU_MODEL_NAME = "ANTHROPIC_DEFAULT_HAIKU_MODEL_NAME"

	// CLAUDE_CODE_DEFAULT_HAIKU_MODEL_DESCRIPTION sets the description for the default Haiku model.
	CLAUDE_CODE_DEFAULT_HAIKU_MODEL_DESCRIPTION = "ANTHROPIC_DEFAULT_HAIKU_MODEL_DESCRIPTION"

	// CLAUDE_CODE_DEFAULT_OPUS_MODEL overrides the default Opus model.
	CLAUDE_CODE_DEFAULT_OPUS_MODEL = "ANTHROPIC_DEFAULT_OPUS_MODEL"

	// CLAUDE_CODE_DEFAULT_OPUS_MODEL_NAME sets the display name for the default Opus model.
	CLAUDE_CODE_DEFAULT_OPUS_MODEL_NAME = "ANTHROPIC_DEFAULT_OPUS_MODEL_NAME"

	// CLAUDE_CODE_DEFAULT_OPUS_MODEL_DESCRIPTION sets the description for the default Opus model.
	CLAUDE_CODE_DEFAULT_OPUS_MODEL_DESCRIPTION = "ANTHROPIC_DEFAULT_OPUS_MODEL_DESCRIPTION"

	// CLAUDE_CODE_DEFAULT_SONNET_MODEL overrides the default Sonnet model.
	CLAUDE_CODE_DEFAULT_SONNET_MODEL = "ANTHROPIC_DEFAULT_SONNET_MODEL"

	// CLAUDE_CODE_DEFAULT_SONNET_MODEL_NAME sets the display name for the default Sonnet model.
	CLAUDE_CODE_DEFAULT_SONNET_MODEL_NAME = "ANTHROPIC_DEFAULT_SONNET_MODEL_NAME"

	// CLAUDE_CODE_DEFAULT_SONNET_MODEL_DESCRIPTION sets the description for the default Sonnet model.
	CLAUDE_CODE_DEFAULT_SONNET_MODEL_DESCRIPTION = "ANTHROPIC_DEFAULT_SONNET_MODEL_DESCRIPTION"

	// CLAUDE_CODE_SUBAGENT_MODEL overrides the model for sub-agents.
	CLAUDE_CODE_SUBAGENT_MODEL = "CLAUDE_CODE_SUBAGENT_MODEL"

	// CLAUDE_CODE_AUTO_MODE_MODEL overrides the model for auto mode.
	CLAUDE_CODE_AUTO_MODE_MODEL = "CLAUDE_CODE_AUTO_MODE_MODEL"

	// CLAUDE_CODE_EFFORT_LEVEL sets the effort level (low, medium, high, max).
	CLAUDE_CODE_EFFORT_LEVEL = "CLAUDE_CODE_EFFORT_LEVEL"

	// CLAUDE_CODE_ALWAYS_ENABLE_EFFORT always enables effort setting.
	CLAUDE_CODE_ALWAYS_ENABLE_EFFORT = "CLAUDE_CODE_ALWAYS_ENABLE_EFFORT"

	// CLAUDE_CODE_MAX_CONTEXT_TOKENS sets the max context window tokens.
	CLAUDE_CODE_MAX_CONTEXT_TOKENS = "CLAUDE_CODE_MAX_CONTEXT_TOKENS"

	// CLAUDE_CODE_MAX_OUTPUT_TOKENS sets the max output tokens.
	CLAUDE_CODE_MAX_OUTPUT_TOKENS = "CLAUDE_CODE_MAX_OUTPUT_TOKENS"

	// CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE overrides the blocking limit.
	CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE = "CLAUDE_CODE_BLOCKING_LIMIT_OVERRIDE"

	// CLAUDE_CODE_TWO_STAGE_CLASSIFIER enables two-stage classification.
	CLAUDE_CODE_TWO_STAGE_CLASSIFIER = "CLAUDE_CODE_TWO_STAGE_CLASSIFIER"

	// CLAUDE_CODE_FILE_READ_MAX_OUTPUT_TOKENS limits file read output tokens.
	CLAUDE_CODE_FILE_READ_MAX_OUTPUT_TOKENS = "CLAUDE_CODE_FILE_READ_MAX_OUTPUT_TOKENS"
)

// ═══════════════════════════════════════════════════
//   Cloud Providers
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_USE_BEDROCK enables AWS Bedrock as the provider.
	CLAUDE_CODE_USE_BEDROCK = "CLAUDE_CODE_USE_BEDROCK"

	// CLAUDE_CODE_USE_VERTEX enables Google Vertex AI as the provider.
	CLAUDE_CODE_USE_VERTEX = "CLAUDE_CODE_USE_VERTEX"

	// CLAUDE_CODE_USE_FOUNDRY enables Anthropic Foundry as the provider.
	CLAUDE_CODE_USE_FOUNDRY = "CLAUDE_CODE_USE_FOUNDRY"

	// CLAUDE_CODE_SKIP_BEDROCK_AUTH skips Bedrock authentication.
	CLAUDE_CODE_SKIP_BEDROCK_AUTH = "CLAUDE_CODE_SKIP_BEDROCK_AUTH"

	// CLAUDE_CODE_SKIP_VERTEX_AUTH skips Vertex authentication.
	CLAUDE_CODE_SKIP_VERTEX_AUTH = "CLAUDE_CODE_SKIP_VERTEX_AUTH"

	// CLAUDE_CODE_SKIP_FOUNDRY_AUTH skips Foundry authentication.
	CLAUDE_CODE_SKIP_FOUNDRY_AUTH = "CLAUDE_CODE_SKIP_FOUNDRY_AUTH"

	// CLAUDE_CODE_ANTHROPIC_BEDROCK_BASE_URL overrides the Bedrock base URL.
	CLAUDE_CODE_ANTHROPIC_BEDROCK_BASE_URL = "ANTHROPIC_BEDROCK_BASE_URL"

	// CLAUDE_CODE_ANTHROPIC_FOUNDRY_BASE_URL overrides the Foundry base URL.
	CLAUDE_CODE_ANTHROPIC_FOUNDRY_BASE_URL = "ANTHROPIC_FOUNDRY_BASE_URL"

	// CLAUDE_CODE_ANTHROPIC_FOUNDRY_API_KEY sets the Foundry API key.
	CLAUDE_CODE_ANTHROPIC_FOUNDRY_API_KEY = "ANTHROPIC_FOUNDRY_API_KEY"

	// CLAUDE_CODE_ANTHROPIC_FOUNDRY_RESOURCE sets the Foundry resource.
	CLAUDE_CODE_ANTHROPIC_FOUNDRY_RESOURCE = "ANTHROPIC_FOUNDRY_RESOURCE"

	// CLAUDE_CODE_ANTHROPIC_VERTEX_PROJECT_ID sets the Vertex project ID.
	CLAUDE_CODE_ANTHROPIC_VERTEX_PROJECT_ID = "ANTHROPIC_VERTEX_PROJECT_ID"
)

// ═══════════════════════════════════════════════════
//   Session & Debugging
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_DEBUG enables debug mode.
	CLAUDE_CODE_DEBUG = "CLAUDE_DEBUG"

	// CLAUDE_CODE_DEBUG_LOGS_DIR sets the debug log directory.
	CLAUDE_CODE_DEBUG_LOGS_DIR = "CLAUDE_CODE_DEBUG_LOGS_DIR"

	// CLAUDE_CODE_DEBUG_LOG_LEVEL sets the debug log level.
	CLAUDE_CODE_DEBUG_LOG_LEVEL = "CLAUDE_CODE_DEBUG_LOG_LEVEL"

	// CLAUDE_CODE_DEBUG_REPAINTS enables debug repainting.
	CLAUDE_CODE_DEBUG_REPAINTS = "CLAUDE_CODE_DEBUG_REPAINTS"

	// CLAUDE_CODE_SESSION_ID sets the session ID.
	CLAUDE_CODE_SESSION_ID = "CLAUDE_CODE_SESSION_ID"

	// CLAUDE_CODE_SESSION_NAME sets the session name.
	CLAUDE_CODE_SESSION_NAME = "CLAUDE_CODE_SESSION_NAME"

	// CLAUDE_CODE_SESSION_KIND sets the session kind.
	CLAUDE_CODE_SESSION_KIND = "CLAUDE_CODE_SESSION_KIND"

	// CLAUDE_CODE_PARENT_SESSION_ID sets the parent session for sub-agents.
	CLAUDE_CODE_PARENT_SESSION_ID = "CLAUDE_CODE_PARENT_SESSION_ID"

	// CLAUDE_CODE_REMOTE_SESSION_ID sets the remote session ID.
	CLAUDE_CODE_REMOTE_SESSION_ID = "CLAUDE_CODE_REMOTE_SESSION_ID"

	// CLAUDE_CODE_JSONL_TRANSCRIPT enables JSONL transcript output.
	CLAUDE_CODE_JSONL_TRANSCRIPT = "CLAUDE_CODE_JSONL_TRANSCRIPT"

	// CLAUDE_CODE_SESSION_LOG enables session logging.
	CLAUDE_CODE_SESSION_LOG = "CLAUDE_CODE_SESSION_LOG"

	// CLAUDE_CODE_COMMIT_LOG enables commit logging.
	CLAUDE_CODE_COMMIT_LOG = "CLAUDE_CODE_COMMIT_LOG"

	// CLAUDE_CODE_DIAGNOSTICS_FILE sets the diagnostics file path.
	CLAUDE_CODE_DIAGNOSTICS_FILE = "CLAUDE_CODE_DIAGNOSTICS_FILE"

	// CLAUDE_CODE_PROFILE_STARTUP enables startup profiling.
	CLAUDE_CODE_PROFILE_STARTUP = "CLAUDE_CODE_PROFILE_STARTUP"

	// CLAUDE_CODE_PROFILE_QUERY enables query profiling.
	CLAUDE_CODE_PROFILE_QUERY = "CLAUDE_CODE_PROFILE_QUERY"

	// CLAUDE_CODE_FRAME_TIMING_LOG sets the frame timing log path.
	CLAUDE_CODE_FRAME_TIMING_LOG = "CLAUDE_CODE_FRAME_TIMING_LOG"
)

// ═══════════════════════════════════════════════════
//   Feature Flags
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_DISABLE_AUTO_MEMORY disables auto memory.
	CLAUDE_CODE_DISABLE_AUTO_MEMORY = "CLAUDE_CODE_DISABLE_AUTO_MEMORY"

	// CLAUDE_CODE_DISABLE_BACKGROUND_TASKS disables background tasks.
	CLAUDE_CODE_DISABLE_BACKGROUND_TASKS = "CLAUDE_CODE_DISABLE_BACKGROUND_TASKS"

	// CLAUDE_CODE_DISABLE_CRON disables cron jobs.
	CLAUDE_CODE_DISABLE_CRON = "CLAUDE_CODE_DISABLE_CRON"

	// CLAUDE_CODE_DISABLE_FAST_MODE disables fast mode.
	CLAUDE_CODE_DISABLE_FAST_MODE = "CLAUDE_CODE_DISABLE_FAST_MODE"

	// CLAUDE_CODE_DISABLE_THINKING disables thinking/reasoning.
	CLAUDE_CODE_DISABLE_THINKING = "CLAUDE_CODE_DISABLE_THINKING"

	// CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING disables adaptive thinking.
	CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING = "CLAUDE_CODE_DISABLE_ADAPTIVE_THINKING"

	// CLAUDE_CODE_DISABLE_CLAUDE_MDS disables reading CLAUDE.md files.
	CLAUDE_CODE_DISABLE_CLAUDE_MDS = "CLAUDE_CODE_DISABLE_CLAUDE_MDS"

	// CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS disables git-based instructions.
	CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS = "CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS"

	// CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC disables non-essential network traffic.
	CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC"

	// CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK disables non-streaming fallback.
	CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK = "CLAUDE_CODE_DISABLE_NONSTREAMING_FALLBACK"

	// CLAUDE_CODE_DISABLE_ADVISOR_TOOL disables the advisor tool.
	CLAUDE_CODE_DISABLE_ADVISOR_TOOL = "CLAUDE_CODE_DISABLE_ADVISOR_TOOL"

	// CLAUDE_CODE_DISABLE_ATTACHMENTS disables attachments.
	CLAUDE_CODE_DISABLE_ATTACHMENTS = "CLAUDE_CODE_DISABLE_ATTACHMENTS"

	// CLAUDE_CODE_DISABLE_COMMAND_INJECTION_CHECK disables command injection checking.
	CLAUDE_CODE_DISABLE_COMMAND_INJECTION_CHECK = "CLAUDE_CODE_DISABLE_COMMAND_INJECTION_CHECK"

	// CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS disables experimental beta features.
	CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS = "CLAUDE_CODE_DISABLE_EXPERIMENTAL_BETAS"

	// CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY disables feedback surveys.
	CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY = "CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY"

	// CLAUDE_CODE_DISABLE_FILE_CHECKPOINTING disables file checkpointing.
	CLAUDE_CODE_DISABLE_FILE_CHECKPOINTING = "CLAUDE_CODE_DISABLE_FILE_CHECKPOINTING"

	// CLAUDE_CODE_DISABLE_LEGACY_MODEL_REMAP disables legacy model remapping.
	CLAUDE_CODE_DISABLE_LEGACY_MODEL_REMAP = "CLAUDE_CODE_DISABLE_LEGACY_MODEL_REMAP"

	// CLAUDE_CODE_DISABLE_MESSAGE_ACTIONS disables message actions.
	CLAUDE_CODE_DISABLE_MESSAGE_ACTIONS = "CLAUDE_CODE_DISABLE_MESSAGE_ACTIONS"

	// CLAUDE_CODE_DISABLE_MOUSE disables mouse input.
	CLAUDE_CODE_DISABLE_MOUSE = "CLAUDE_CODE_DISABLE_MOUSE"

	// CLAUDE_CODE_DISABLE_MOUSE_CLICKS disables mouse click handling.
	CLAUDE_CODE_DISABLE_MOUSE_CLICKS = "CLAUDE_CODE_DISABLE_MOUSE_CLICKS"

	// CLAUDE_CODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL disables official marketplace auto-install.
	CLAUDE_CODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL = "CLAUDE_CODE_DISABLE_OFFICIAL_MARKETPLACE_AUTOINSTALL"

	// CLAUDE_CODE_DISABLE_POLICY_SKILLS disables policy skills.
	CLAUDE_CODE_DISABLE_POLICY_SKILLS = "CLAUDE_CODE_DISABLE_POLICY_SKILLS"

	// CLAUDE_CODE_DISABLE_PRECOMPACT_SKIP disables pre-compact skip optimization.
	CLAUDE_CODE_DISABLE_PRECOMPACT_SKIP = "CLAUDE_CODE_DISABLE_PRECOMPACT_SKIP"

	// CLAUDE_CODE_DISABLE_TERMINAL_TITLE disables terminal title updates.
	CLAUDE_CODE_DISABLE_TERMINAL_TITLE = "CLAUDE_CODE_DISABLE_TERMINAL_TITLE"

	// CLAUDE_CODE_DISABLE_VIRTUAL_SCROLL disables virtual scrolling.
	CLAUDE_CODE_DISABLE_VIRTUAL_SCROLL = "CLAUDE_CODE_DISABLE_VIRTUAL_SCROLL"

	// CLAUDE_CODE_ENABLE_TASKS enables task tracking.
	CLAUDE_CODE_ENABLE_TASKS = "CLAUDE_CODE_ENABLE_TASKS"

	// CLAUDE_CODE_ENABLE_TELEMETRY enables telemetry collection.
	CLAUDE_CODE_ENABLE_TELEMETRY = "CLAUDE_CODE_ENABLE_TELEMETRY"

	// CLAUDE_CODE_ENABLE_CFC enables CFC.
	CLAUDE_CODE_ENABLE_CFC = "CLAUDE_CODE_ENABLE_CFC"

	// CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING enables fine-grained tool streaming.
	CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING = "CLAUDE_CODE_ENABLE_FINE_GRAINED_TOOL_STREAMING"

	// CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION enables prompt suggestions.
	CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION = "CLAUDE_CODE_ENABLE_PROMPT_SUGGESTION"

	// CLAUDE_CODE_ENABLE_TOKEN_USAGE_ATTACHMENT enables token usage attachment.
	CLAUDE_CODE_ENABLE_TOKEN_USAGE_ATTACHMENT = "CLAUDE_CODE_ENABLE_TOKEN_USAGE_ATTACHMENT"

	// CLAUDE_CODE_ENABLE_XAA enables XAA.
	CLAUDE_CODE_ENABLE_XAA = "CLAUDE_CODE_ENABLE_XAA"

	// CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES enables partial message streaming.
	CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES = "CLAUDE_CODE_INCLUDE_PARTIAL_MESSAGES"
)

// ═══════════════════════════════════════════════════
//   Agent & Coordination
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS enables experimental agent teams.
	CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS = "CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS"

	// CLAUDE_CODE_AGENT sets the agent name.
	CLAUDE_CODE_AGENT = "CLAUDE_CODE_AGENT"

	// CLAUDE_CODE_AGENT_LIST_IN_MESSAGES enables agent list in messages.
	CLAUDE_CODE_AGENT_LIST_IN_MESSAGES = "CLAUDE_CODE_AGENT_LIST_IN_MESSAGES"

	// CLAUDE_CODE_COORDINATOR_MODE sets the coordinator mode.
	CLAUDE_CODE_COORDINATOR_MODE = "CLAUDE_CODE_COORDINATOR_MODE"

	// CLAUDE_CODE_COWORKER_TYPE sets the coworker type.
	CLAUDE_CODE_COWORKER_TYPE = "CLAUDE_CODE_COWORKER_TYPE"

	// CLAUDE_CODE_IS_COWORK indicates the session is a cowork session.
	CLAUDE_CODE_IS_COWORK = "CLAUDE_CODE_IS_COWORK"

	// CLAUDE_CODE_USE_COWORK_PLUGINS enables cowork plugins.
	CLAUDE_CODE_USE_COWORK_PLUGINS = "CLAUDE_CODE_USE_COWORK_PLUGINS"

	// CLAUDE_CODE_PROACTIVE enables proactive mode.
	CLAUDE_CODE_PROACTIVE = "CLAUDE_CODE_PROACTIVE"

	// CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY limits tool use concurrency.
	CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY = "CLAUDE_CODE_MAX_TOOL_USE_CONCURRENCY"

	// CLAUDE_CODE_WORKER_EPOCH sets the worker epoch.
	CLAUDE_CODE_WORKER_EPOCH = "CLAUDE_CODE_WORKER_EPOCH"

	// CLAUDE_CODE_TASK_LIST_ID sets the task list ID.
	CLAUDE_CODE_TASK_LIST_ID = "CLAUDE_CODE_TASK_LIST_ID"
)

// ═══════════════════════════════════════════════════
//   Sandbox & Environment
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_FORCE_SANDBOX forces sandbox mode.
	CLAUDE_CODE_FORCE_SANDBOX = "CLAUDE_CODE_FORCE_SANDBOX"

	// CLAUDE_CODE_BUBBLEWRAP enables bubblewrap sandbox on Linux.
	CLAUDE_CODE_BUBBLEWRAP = "CLAUDE_CODE_BUBBLEWRAP"

	// CLAUDE_CODE_BASH_SANDBOX_SHOW_INDICATOR shows sandbox indicator for bash.
	CLAUDE_CODE_BASH_SANDBOX_SHOW_INDICATOR = "CLAUDE_CODE_BASH_SANDBOX_SHOW_INDICATOR"

	// CLAUDE_CODE_ADDITIONAL_PROTECTION enables additional protection measures.
	CLAUDE_CODE_ADDITIONAL_PROTECTION = "CLAUDE_CODE_ADDITIONAL_PROTECTION"

	// CLAUDE_CODE_SHELL overrides the shell used for bash commands.
	CLAUDE_CODE_SHELL = "CLAUDE_CODE_SHELL"

	// CLAUDE_CODE_SHELL_PREFIX sets the shell command prefix.
	CLAUDE_CODE_SHELL_PREFIX = "CLAUDE_CODE_SHELL_PREFIX"

	// CLAUDE_CODE_TMPDIR overrides the temporary directory.
	CLAUDE_CODE_TMPDIR = "CLAUDE_CODE_TMPDIR"

	// CLAUDE_CODE_ENVIRONMENT_KIND describes the environment (e.g., "docker", "ssh").
	CLAUDE_CODE_ENVIRONMENT_KIND = "CLAUDE_CODE_ENVIRONMENT_KIND"

	// CLAUDE_CODE_ENVIRONMENT_RUNNER_VERSION sets the environment runner version.
	CLAUDE_CODE_ENVIRONMENT_RUNNER_VERSION = "CLAUDE_CODE_ENVIRONMENT_RUNNER_VERSION"

	// CLAUDE_CODE_REMOTE enables remote mode.
	CLAUDE_CODE_REMOTE = "CLAUDE_CODE_REMOTE"

	// CLAUDE_CODE_REMOTE_ENVIRONMENT_TYPE sets the remote environment type.
	CLAUDE_CODE_REMOTE_ENVIRONMENT_TYPE = "CLAUDE_CODE_REMOTE_ENVIRONMENT_TYPE"

	// CLAUDE_CODE_REMOTE_MEMORY_DIR sets the remote memory directory.
	CLAUDE_CODE_REMOTE_MEMORY_DIR = "CLAUDE_CODE_REMOTE_MEMORY_DIR"

	// CLAUDE_CODE_REMOTE_SEND_KEEPALIVES enables keepalive messages in remote mode.
	CLAUDE_CODE_REMOTE_SEND_KEEPALIVES = "CLAUDE_CODE_REMOTE_SEND_KEEPALIVES"

	// CLAUDE_CODE_HOST_PLATFORM sets the host platform identifier.
	CLAUDE_CODE_HOST_PLATFORM = "CLAUDE_CODE_HOST_PLATFORM"

	// CLAUDE_CODE_CONTAINER_ID sets the container ID.
	CLAUDE_CODE_CONTAINER_ID = "CLAUDE_CODE_CONTAINER_ID"

	// CLAUDE_CODE_WORKSPACE_HOST_PATHS sets workspace host paths.
	CLAUDE_CODE_WORKSPACE_HOST_PATHS = "CLAUDE_CODE_WORKSPACE_HOST_PATHS"

	// CLAUDE_CODE_DONT_INHERIT_ENV prevents environment variable inheritance.
	CLAUDE_CODE_DONT_INHERIT_ENV = "CLAUDE_CODE_DONT_INHERIT_ENV"

	// CLAUDE_CODE_SUBPROCESS_ENV_SCRUB scrubs environment variables for subprocesses.
	CLAUDE_CODE_SUBPROCESS_ENV_SCRUB = "CLAUDE_CODE_SUBPROCESS_ENV_SCRUB"

	// CLAUDE_CODE_MANAGED_SETTINGS_PATH sets the managed settings file path.
	CLAUDE_CODE_MANAGED_SETTINGS_PATH = "CLAUDE_CODE_MANAGED_SETTINGS_PATH"

	// CLAUDE_CODE_GIT_BASH_PATH sets the path to git bash on Windows.
	CLAUDE_CODE_GIT_BASH_PATH = "CLAUDE_CODE_GIT_BASH_PATH"

	// CLAUDE_CODE_USE_POWERSHELL_TOOL enables PowerShell tool.
	CLAUDE_CODE_USE_POWERSHELL_TOOL = "CLAUDE_CODE_USE_POWERSHELL_TOOL"

	// CLAUDE_CODE_PWSH_PARSE_TIMEOUT_MS sets the PowerShell parse timeout in ms.
	CLAUDE_CODE_PWSH_PARSE_TIMEOUT_MS = "CLAUDE_CODE_PWSH_PARSE_TIMEOUT_MS"

	// CLAUDE_CODE_USE_NATIVE_FILE_SEARCH enables native file search.
	CLAUDE_CODE_USE_NATIVE_FILE_SEARCH = "CLAUDE_CODE_USE_NATIVE_FILE_SEARCH"
)

// ═══════════════════════════════════════════════════
//   MCP (Model Context Protocol)
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_MCP_TIMEOUT sets the MCP server connection timeout.
	CLAUDE_CODE_MCP_TIMEOUT = "MCP_TIMEOUT"

	// CLAUDE_CODE_MCP_TOOL_TIMEOUT sets the MCP tool execution timeout.
	CLAUDE_CODE_MCP_TOOL_TIMEOUT = "MCP_TOOL_TIMEOUT"

	// CLAUDE_CODE_MAX_MCP_OUTPUT_TOKENS limits MCP output tokens.
	CLAUDE_CODE_MAX_MCP_OUTPUT_TOKENS = "MAX_MCP_OUTPUT_TOKENS"

	// CLAUDE_CODE_MCP_INSTR_DELTA sets the MCP instruction delta.
	CLAUDE_CODE_MCP_INSTR_DELTA = "CLAUDE_CODE_MCP_INSTR_DELTA"
)

// ═══════════════════════════════════════════════════
//   Bash Tool
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_BASH_DEFAULT_TIMEOUT_MS sets the default bash command timeout.
	CLAUDE_CODE_BASH_DEFAULT_TIMEOUT_MS = "BASH_DEFAULT_TIMEOUT_MS"

	// CLAUDE_CODE_BASH_MAX_TIMEOUT_MS sets the max bash command timeout.
	CLAUDE_CODE_BASH_MAX_TIMEOUT_MS = "BASH_MAX_TIMEOUT_MS"

	// CLAUDE_CODE_BASH_MAX_OUTPUT_LENGTH limits bash command output length.
	CLAUDE_CODE_BASH_MAX_OUTPUT_LENGTH = "BASH_MAX_OUTPUT_LENGTH"
)

// ═══════════════════════════════════════════════════
//   Proxy & TLS
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_HTTP_PROXY sets the HTTP proxy.
	CLAUDE_CODE_HTTP_PROXY = "HTTP_PROXY"

	// CLAUDE_CODE_HTTPS_PROXY sets the HTTPS proxy.
	CLAUDE_CODE_HTTPS_PROXY = "HTTPS_PROXY"

	// CLAUDE_CODE_NO_PROXY sets the no-proxy list.
	CLAUDE_CODE_NO_PROXY = "NO_PROXY"

	// CLAUDE_CODE_CLIENT_CERT sets the client certificate path for mTLS.
	CLAUDE_CODE_CLIENT_CERT = "CLAUDE_CODE_CLIENT_CERT"

	// CLAUDE_CODE_CLIENT_KEY sets the client key path for mTLS.
	CLAUDE_CODE_CLIENT_KEY = "CLAUDE_CODE_CLIENT_KEY"

	// CLAUDE_CODE_CLIENT_KEY_PASSPHRASE sets the client key passphrase for mTLS.
	CLAUDE_CODE_CLIENT_KEY_PASSPHRASE = "CLAUDE_CODE_CLIENT_KEY_PASSPHRASE"

	// CLAUDE_CODE_PROXY_RESOLVES_HOSTS indicates that the proxy resolves hosts.
	CLAUDE_CODE_PROXY_RESOLVES_HOSTS = "CLAUDE_CODE_PROXY_RESOLVES_HOSTS"
)

// ═══════════════════════════════════════════════════
//   Telemetry & Observability (OpenTelemetry)
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_OTEL_ENDPOINT sets the OTLP exporter endpoint.
	CLAUDE_CODE_OTEL_ENDPOINT = "OTEL_EXPORTER_OTLP_ENDPOINT"

	// CLAUDE_CODE_OTEL_HEADERS sets the OTLP exporter headers.
	CLAUDE_CODE_OTEL_HEADERS = "OTEL_EXPORTER_OTLP_HEADERS"

	// CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS sets the OTEL flush timeout in ms.
	CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS = "CLAUDE_CODE_OTEL_FLUSH_TIMEOUT_MS"

	// CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS sets the OTEL shutdown timeout in ms.
	CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS = "CLAUDE_CODE_OTEL_SHUTDOWN_TIMEOUT_MS"

	// CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS sets the OTEL headers helper debounce in ms.
	CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS = "CLAUDE_CODE_OTEL_HEADERS_HELPER_DEBOUNCE_MS"

	// CLAUDE_CODE_ENHANCED_TELEMETRY_BETA enables enhanced telemetry beta.
	CLAUDE_CODE_ENHANCED_TELEMETRY_BETA = "CLAUDE_CODE_ENHANCED_TELEMETRY_BETA"

	// CLAUDE_CODE_DATADOG_FLUSH_INTERVAL_MS sets the Datadog flush interval in ms.
	CLAUDE_CODE_DATADOG_FLUSH_INTERVAL_MS = "CLAUDE_CODE_DATADOG_FLUSH_INTERVAL_MS"

	// CLAUDE_CODE_PERFETTO_TRACE enables Perfetto trace output.
	CLAUDE_CODE_PERFETTO_TRACE = "CLAUDE_CODE_PERFETTO_TRACE"

	// CLAUDE_CODE_PERFETTO_WRITE_INTERVAL_S sets the Perfetto write interval in seconds.
	CLAUDE_CODE_PERFETTO_WRITE_INTERVAL_S = "CLAUDE_CODE_PERFETTO_WRITE_INTERVAL_S"
)

// ═══════════════════════════════════════════════════
//   Prompt Caching & Misc Disables
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_DISABLE_PROMPT_CACHING disables prompt caching.
	CLAUDE_CODE_DISABLE_PROMPT_CACHING = "DISABLE_PROMPT_CACHING"

	// CLAUDE_CODE_DISABLE_TELEMETRY disables telemetry.
	CLAUDE_CODE_DISABLE_TELEMETRY = "DISABLE_TELEMETRY"

	// CLAUDE_CODE_DISABLE_ERROR_REPORTING disables error reporting.
	CLAUDE_CODE_DISABLE_ERROR_REPORTING = "DISABLE_ERROR_REPORTING"
)

// ═══════════════════════════════════════════════════
//   UI & Output
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_BRIEF enables brief output mode.
	CLAUDE_CODE_BRIEF = "CLAUDE_CODE_BRIEF"

	// CLAUDE_CODE_BRIEF_UPLOAD enables brief upload mode.
	CLAUDE_CODE_BRIEF_UPLOAD = "CLAUDE_CODE_BRIEF_UPLOAD"

	// CLAUDE_CODE_SIMPLE enables simple output mode.
	CLAUDE_CODE_SIMPLE = "CLAUDE_CODE_SIMPLE"

	// CLAUDE_CODE_STREAMLINED_OUTPUT enables streamlined output.
	CLAUDE_CODE_STREAMLINED_OUTPUT = "CLAUDE_CODE_STREAMLINED_OUTPUT"

	// CLAUDE_CODE_ACCESSIBILITY enables accessibility features.
	CLAUDE_CODE_ACCESSIBILITY = "CLAUDE_CODE_ACCESSIBILITY"

	// CLAUDE_CODE_SYNTAX_HIGHLIGHT enables syntax highlighting.
	CLAUDE_CODE_SYNTAX_HIGHLIGHT = "CLAUDE_CODE_SYNTAX_HIGHLIGHT"

	// CLAUDE_CODE_NO_FLICKER disables flickering in output.
	CLAUDE_CODE_NO_FLICKER = "CLAUDE_CODE_NO_FLICKER"

	// CLAUDE_CODE_SCROLL_SPEED sets the scroll speed.
	CLAUDE_CODE_SCROLL_SPEED = "CLAUDE_CODE_SCROLL_SPEED"

	// CLAUDE_CODE_FORCE_FULL_LOGO forces the full logo display.
	CLAUDE_CODE_FORCE_FULL_LOGO = "CLAUDE_CODE_FORCE_FULL_LOGO"

	// CLAUDE_CODE_QUESTION_PREVIEW_FORMAT sets the question preview format.
	CLAUDE_CODE_QUESTION_PREVIEW_FORMAT = "CLAUDE_CODE_QUESTION_PREVIEW_FORMAT"

	// CLAUDE_CODE_EMIT_TOOL_USE_SUMMARIES enables tool use summaries.
	CLAUDE_CODE_EMIT_TOOL_USE_SUMMARIES = "CLAUDE_CODE_EMIT_TOOL_USE_SUMMARIES"

	// CLAUDE_CODE_EMIT_SESSION_STATE_EVENTS enables session state events.
	CLAUDE_CODE_EMIT_SESSION_STATE_EVENTS = "CLAUDE_CODE_EMIT_SESSION_STATE_EVENTS"

	// CLAUDE_CODE_TERMINAL_RECORDING enables terminal recording.
	CLAUDE_CODE_TERMINAL_RECORDING = "CLAUDE_CODE_TERMINAL_RECORDING"
)

// ═══════════════════════════════════════════════════
//   IDE Integration
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_AUTO_CONNECT_IDE enables automatic IDE connection.
	CLAUDE_CODE_AUTO_CONNECT_IDE = "CLAUDE_CODE_AUTO_CONNECT_IDE"

	// CLAUDE_CODE_IDE_HOST_OVERRIDE overrides the IDE host.
	CLAUDE_CODE_IDE_HOST_OVERRIDE = "CLAUDE_CODE_IDE_HOST_OVERRIDE"

	// CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL skips IDE auto-installation.
	CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL = "CLAUDE_CODE_IDE_SKIP_AUTO_INSTALL"

	// CLAUDE_CODE_IDE_SKIP_VALID_CHECK skips IDE validity check.
	CLAUDE_CODE_IDE_SKIP_VALID_CHECK = "CLAUDE_CODE_IDE_SKIP_VALID_CHECK"
)

// ═══════════════════════════════════════════════════
//   Plugin System
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_PLUGIN_CACHE_DIR sets the plugin cache directory.
	CLAUDE_CODE_PLUGIN_CACHE_DIR = "CLAUDE_CODE_PLUGIN_CACHE_DIR"

	// CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS sets the plugin git timeout in ms.
	CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS = "CLAUDE_CODE_PLUGIN_GIT_TIMEOUT_MS"

	// CLAUDE_CODE_PLUGIN_SEED_DIR sets the plugin seed directory.
	CLAUDE_CODE_PLUGIN_SEED_DIR = "CLAUDE_CODE_PLUGIN_SEED_DIR"

	// CLAUDE_CODE_PLUGIN_USE_ZIP_CACHE enables plugin zip caching.
	CLAUDE_CODE_PLUGIN_USE_ZIP_CACHE = "CLAUDE_CODE_PLUGIN_USE_ZIP_CACHE"

	// CLAUDE_CODE_SYNC_PLUGIN_INSTALL enables synchronous plugin installation.
	CLAUDE_CODE_SYNC_PLUGIN_INSTALL = "CLAUDE_CODE_SYNC_PLUGIN_INSTALL"

	// CLAUDE_CODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS sets the sync plugin install timeout in ms.
	CLAUDE_CODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS = "CLAUDE_CODE_SYNC_PLUGIN_INSTALL_TIMEOUT_MS"
)

// ═══════════════════════════════════════════════════
//   TMUX Integration
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_TMUX_SESSION sets the tmux session name.
	CLAUDE_CODE_TMUX_SESSION = "CLAUDE_CODE_TMUX_SESSION"

	// CLAUDE_CODE_TMUX_PREFIX sets the tmux prefix key.
	CLAUDE_CODE_TMUX_PREFIX = "CLAUDE_CODE_TMUX_PREFIX"

	// CLAUDE_CODE_TMUX_PREFIX_CONFLICTS indicates tmux prefix key conflicts.
	CLAUDE_CODE_TMUX_PREFIX_CONFLICTS = "CLAUDE_CODE_TMUX_PREFIX_CONFLICTS"

	// CLAUDE_CODE_TMUX_TRUECOLOR enables truecolor in tmux.
	CLAUDE_CODE_TMUX_TRUECOLOR = "CLAUDE_CODE_TMUX_TRUECOLOR"
)

// ═══════════════════════════════════════════════════
//   Glob & File Search
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_GLOB_HIDDEN includes hidden files in glob searches.
	CLAUDE_CODE_GLOB_HIDDEN = "CLAUDE_CODE_GLOB_HIDDEN"

	// CLAUDE_CODE_GLOB_NO_IGNORE disables gitignore filtering for glob searches.
	CLAUDE_CODE_GLOB_NO_IGNORE = "CLAUDE_CODE_GLOB_NO_IGNORE"

	// CLAUDE_CODE_GLOB_TIMEOUT_SECONDS sets the glob search timeout in seconds.
	CLAUDE_CODE_GLOB_TIMEOUT_SECONDS = "CLAUDE_CODE_GLOB_TIMEOUT_SECONDS"
)

// ═══════════════════════════════════════════════════
//   Plan Mode
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_PLAN_MODE_REQUIRED requires plan mode.
	CLAUDE_CODE_PLAN_MODE_REQUIRED = "CLAUDE_CODE_PLAN_MODE_REQUIRED"

	// CLAUDE_CODE_PLAN_MODE_INTERVIEW_PHASE enables interview phase in plan mode.
	CLAUDE_CODE_PLAN_MODE_INTERVIEW_PHASE = "CLAUDE_CODE_PLAN_MODE_INTERVIEW_PHASE"

	// CLAUDE_CODE_PLAN_V sets the plan version.
	CLAUDE_CODE_PLAN_V = "CLAUDE_CODE_PLAN_V"

	// CLAUDE_CODE_VERIFY_PLAN enables plan verification.
	CLAUDE_CODE_VERIFY_PLAN = "CLAUDE_CODE_VERIFY_PLAN"
)

// ═══════════════════════════════════════════════════
//   Experimental & Internal
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_ABLATION_BASELINE sets the ablation baseline for experiments.
	CLAUDE_CODE_ABLATION_BASELINE = "CLAUDE_CODE_ABLATION_BASELINE"

	// CLAUDE_CODE_ACTION sets the action for CLI invocation.
	CLAUDE_CODE_ACTION = "CLAUDE_CODE_ACTION"

	// CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD sets additional CLAUDE.md directories.
	CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD = "CLAUDE_CODE_ADDITIONAL_DIRECTORIES_CLAUDE_MD"

	// CLAUDE_CODE_AUTO_COMPACT_WINDOW sets the auto-compact window size.
	CLAUDE_CODE_AUTO_COMPACT_WINDOW = "CLAUDE_CODE_AUTO_COMPACT_WINDOW"

	// CLAUDE_CODE_BASE_REF sets the base git ref.
	CLAUDE_CODE_BASE_REF = "CLAUDE_CODE_BASE_REF"

	// CLAUDE_CODE_CCR_MIRROR sets the CCR mirror URL.
	CLAUDE_CODE_CCR_MIRROR = "CLAUDE_CODE_CCR_MIRROR"

	// CLAUDE_CODE_USE_CCR_V sets the CCR version.
	CLAUDE_CODE_USE_CCR_V = "CLAUDE_CODE_USE_CCR_V"

	// CLAUDE_CODE_DUMP_AUTO_MODE dumps auto mode configuration.
	CLAUDE_CODE_DUMP_AUTO_MODE = "CLAUDE_CODE_DUMP_AUTO_MODE"

	// CLAUDE_CODE_EAGER_FLUSH enables eager flushing.
	CLAUDE_CODE_EAGER_FLUSH = "CLAUDE_CODE_EAGER_FLUSH"

	// CLAUDE_CODE_EXIT_AFTER_FIRST_RENDER exits after the first render.
	CLAUDE_CODE_EXIT_AFTER_FIRST_RENDER = "CLAUDE_CODE_EXIT_AFTER_FIRST_RENDER"

	// CLAUDE_CODE_EXIT_AFTER_STOP_DELAY sets the exit delay after stop in ms.
	CLAUDE_CODE_EXIT_AFTER_STOP_DELAY = "CLAUDE_CODE_EXIT_AFTER_STOP_DELAY"

	// CLAUDE_CODE_GB_BASE_URL sets the GrowthBook base URL.
	CLAUDE_CODE_GB_BASE_URL = "CLAUDE_CODE_GB_BASE_URL"

	// CLAUDE_CODE_IDLE_THRESHOLD_MINUTES sets the idle timeout threshold.
	CLAUDE_CODE_IDLE_THRESHOLD_MINUTES = "CLAUDE_CODE_IDLE_THRESHOLD_MINUTES"

	// CLAUDE_CODE_IDLE_TOKEN_THRESHOLD sets the idle token threshold.
	CLAUDE_CODE_IDLE_TOKEN_THRESHOLD = "CLAUDE_CODE_IDLE_TOKEN_THRESHOLD"

	// CLAUDE_CODE_MAX_RETRIES sets the max API retry count.
	CLAUDE_CODE_MAX_RETRIES = "CLAUDE_CODE_MAX_RETRIES"

	// CLAUDE_CODE_MESSAGING_SOCKET sets the messaging socket path.
	CLAUDE_CODE_MESSAGING_SOCKET = "CLAUDE_CODE_MESSAGING_SOCKET"

	// CLAUDE_CODE_NEW_INIT uses new initialization flow.
	CLAUDE_CODE_NEW_INIT = "CLAUDE_CODE_NEW_INIT"

	// CLAUDE_CODE_OVERRIDE_DATE overrides the current date.
	CLAUDE_CODE_OVERRIDE_DATE = "CLAUDE_CODE_OVERRIDE_DATE"

	// CLAUDE_CODE_POST_FOR_SESSION_INGRESS_V sets the session ingress post version.
	CLAUDE_CODE_POST_FOR_SESSION_INGRESS_V = "CLAUDE_CODE_POST_FOR_SESSION_INGRESS_V"

	// CLAUDE_CODE_REPL enables REPL mode.
	CLAUDE_CODE_REPL = "CLAUDE_CODE_REPL"

	// CLAUDE_CODE_RESUME_INTERRUPTED_TURN resumes an interrupted turn.
	CLAUDE_CODE_RESUME_INTERRUPTED_TURN = "CLAUDE_CODE_RESUME_INTERRUPTED_TURN"

	// CLAUDE_CODE_SAVE_HOOK_ADDITIONAL_CONTEXT saves hook additional context.
	CLAUDE_CODE_SAVE_HOOK_ADDITIONAL_CONTEXT = "CLAUDE_CODE_SAVE_HOOK_ADDITIONAL_CONTEXT"

	// CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS sets the session end hooks timeout in ms.
	CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS = "CLAUDE_CODE_SESSIONEND_HOOKS_TIMEOUT_MS"

	// CLAUDE_CODE_SKIP_FAST_MODE_NETWORK_ERRORS skips fast mode on network errors.
	CLAUDE_CODE_SKIP_FAST_MODE_NETWORK_ERRORS = "CLAUDE_CODE_SKIP_FAST_MODE_NETWORK_ERRORS"

	// CLAUDE_CODE_SKIP_PROMPT_HISTORY skips prompt history.
	CLAUDE_CODE_SKIP_PROMPT_HISTORY = "CLAUDE_CODE_SKIP_PROMPT_HISTORY"

	// CLAUDE_CODE_SLOW_OPERATION_THRESHOLD_MS sets the slow operation threshold in ms.
	CLAUDE_CODE_SLOW_OPERATION_THRESHOLD_MS = "CLAUDE_CODE_SLOW_OPERATION_THRESHOLD_MS"

	// CLAUDE_CODE_SSE_PORT sets the SSE server port.
	CLAUDE_CODE_SSE_PORT = "CLAUDE_CODE_SSE_PORT"

	// CLAUDE_CODE_STALL_TIMEOUT_MS_FOR_TESTING sets the stall timeout for testing in ms.
	CLAUDE_CODE_STALL_TIMEOUT_MS_FOR_TESTING = "CLAUDE_CODE_STALL_TIMEOUT_MS_FOR_TESTING"

	// CLAUDE_CODE_TEST_FIXTURES_ROOT sets the test fixtures root directory.
	CLAUDE_CODE_TEST_FIXTURES_ROOT = "CLAUDE_CODE_TEST_FIXTURES_ROOT"

	// CLAUDE_CODE_UNDERCOVER enables undercover mode.
	CLAUDE_CODE_UNDERCOVER = "CLAUDE_CODE_UNDERCOVER"

	// CLAUDE_CODE_UNATTENDED_RETRY enables unattended retry.
	CLAUDE_CODE_UNATTENDED_RETRY = "CLAUDE_CODE_UNATTENDED_RETRY"

	// CLAUDE_CODE_RECOVER_FEATURES enables feature recovery.
	CLAUDE_CODE_RECOVER_FEATURES = "CLAUDE_CODE_RECOVER_FEATURES"
)

// ═══════════════════════════════════════════════════
//   Tags & Metadata
// ═══════════════════════════════════════════════════

const (
	// CLAUDE_CODE_TAGS sets session tags.
	CLAUDE_CODE_TAGS = "CLAUDE_CODE_TAGS"

	// CLAUDE_CODE_EXTRA_BODY sets extra body fields for API requests.
	CLAUDE_CODE_EXTRA_BODY = "CLAUDE_CODE_EXTRA_BODY"

	// CLAUDE_CODE_EXTRA_METADATA sets extra metadata for API requests.
	CLAUDE_CODE_EXTRA_METADATA = "CLAUDE_CODE_EXTRA_METADATA"
)

// ═══════════════════════════════════════════════════
//   SDK Constants
// ═══════════════════════════════════════════════════

// SDKVersion is the current version of the Go Agent SDK.
const SDKVersion = "0.1.0"

// MinimumClaudeCodeVersion is the minimum required Claude Code CLI version.
const MinimumClaudeCodeVersion = "2.0.0"

// SDKEntrypoint identifies this SDK in the CLAUDE_CODE_ENTRYPOINT variable.
const SDKEntrypoint = "sdk-go"
